app:
  name: Taxi Online Server

server:
  port: 8080

datasource:
  pool:
    maxSize: 10
    minSize: 2
    initialSize: 5
  url: jdbc:postgresql://localhost:5432/taxi_online
  user: postgres
  password: postgres